version: "3"

services:
  dev-workspace:
    extends:
      file: docker-compose.yml
      service: dev-workspace
    image: mhseals/roboboat-2023:nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    command: tail -f /dev/null
    runtime: nvidia
