name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
        - Dockerfile
        - Dockerfile.nvidia
  pull_request:
    branches: [ "main" ]
    paths:
        - Dockerfile
        - Dockerfile.nvidia  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Checkout repository
        uses: actions/checkout@v2
    -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
        name: Build and Push Docker base image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: Dockerfile
            push: true
            tags: mhseals/roboboat-2023:base
    -
        name: Build and Push Docker NVIDIA image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: Dockerfile.nvidia
            push: true
            tags: mhseals/roboboat-2023:nvidia
